### ISSUE TITLE
MAME 0.189: no pieces on MAME board (academy), nothing happens in xboard

### ISSUE THREAD

**Issue by mdoege** [sronco/mame-chessengine#4]
Hi Sandro!

Thanks for your work on Mephisto chess computer emulation in MAME!

I am trying to use academy together with your plugin and xboard, but the MAME chessboard is empty, the top right LEDs are blinking (meaning the Academy is looking for chess pieces, but they are not there), and nothing happens in xboard after my initial move with white, see screenshot: https://i.imgur.com/3Wnd3Xl.png

I think I have the latest artwork files, so I am not sure why this is not working.

Thanks,
Martin

**Comment by sronco** [comment]
Hi Martin,

I tried sdlmame 0.189 from Arch official repo and yours command line work fine, are you sure you installed the plugin properly? the easy way is to copy the chessengine directory in /usr/share/sdlmame/plugins/

Sandro

**Comment by mdoege** [comment]
You are right, if I put chessengine in the global plugin directory (as opposed to ~/.mame/plugins/), I am getting moves from black! Excellent! (And the moves match what my real Mephisto Academy plays. )

I am still not seeing any pieces in the MAME window itself, but I guess that's normal?

Thanks for your help with this, Sandro!

**Comment by sronco** [comment]
> I am still not seeing any pieces in the MAME window itself, but I guess that's normal?

Yes, chess pieces simulation was removed during the MAME GPL relicensing.

**Comment by mdoege** [comment]
Ah, OK, I did not know that. But as far as I remember, it was a bit buggy anyway. I tried it out on the Novag Constellation emulation last year or so I think.

Speaking of bugs, I have noticed that sometimes when connecting two machines via xboard, say academy and risc, after some time, a move does not get registered. E.g. academy moves, the move shows up in xboard, but for some reason risc does not see it. At which point the game stalls, because now each machine thinks it is the other's move. I have tried setting frameskip to 0 in both machines, but nothing seems to help.

I am not sure if this an xboard or mame-chessengine bug, or maybe an issue in MAME itself. Perhaps mame-chessengine needs more debug statements so it is easier to figure out why a move gets dropped. Otherwise I will never get a completed game between a RISC 2500 and a Mephisto Academy. 😉

**Comment by mdoege** [comment]
P.S. I've switched from XBoard to [KDE Knights](https://www.kde.org/applications/games/knights/), and I am no longer seeing any mysteriously dropped moves. Maybe the problem is that XBoard likes to send Control-C characters to engines? Knights does not send the initial "xboard" command, so mame-chessengine only works in UCI mode. But at least everything runs reliably now and Knights supports two engines fighting each other, which is not an option in e.g. PyChess.
